---
language: vim

before_script:
  - export REPO_DIR=$(pwd)
  - |
    echo 'Build and install vim 7.4.1842.'
    cd ~/
    sudo apt-get remove vim -y
    git clone https://github.com/vim/vim
    cd vim
    export VIM_GIT_DIR=$(cwd)
    git checkout v7.4.1842
    ./configure --with-features=huge --prefix=$HOME/out/7.4.1842
    make install
  - |
    echo 'Build and install vim 8.1+'
    cd $VIM_GIT_DIR
    make distclean
    git checkout master
    ./configure --with-features=huge --prefix=$HOME/out/8
    make install
  - |
    echo 'Add neovim PPA.'
    if [[ `lsb_release -r | awk '{print $2}'` < 16.04 ]]; then
      echo "Using neovim-ppa/unstable for Ubuntu version older than 16.04."
      sudo add-apt-repository ppa:neovim-ppa/unstable -y
    else
      echo "Using neovim-ppa/stable for Ubuntu version 16.04 or newer."
      sudo add-apt-repository ppa:neovim-ppa/stable   -y
    fi
  - sudo apt-get update  -q
  - |
    echo 'Install foreign language packs for international tests.'
    sudo apt-get install -y language-pack-de language-pack-es
  - |
    echo 'Install neovim.'
    sudo apt-get install -y neovim
    nvim --version
  - |
    echo 'Clone dependencies.'
    mkdir -p ~/.vim/bundle
    git clone https://github.com/junegunn/vader.vim ~/.vim/bundle/vader.vim
    git clone https://github.com/Google/vim-maktaba ~/.vim/bundle/vim-maktaba

script:
  - cd "$REPO_DIR/test"  # to make handling filepaths easier
  - |
    VIM_EXE=$HOME/out/7.4.1842/bin/vim
    echo 'Running Vim 7.4 tests.' \
      && $VIM_EXE --version \
      && ./run_tests.sh --vim
        \ --vim_exe=$VIM_EXE --international
  - echo 'Removing vim 7.4 installation.'
    cd ~/vim
    sudo make uninstall
  - |
    echo 'Running neovim tests.' \
      && ./run_tests.sh --neovim --international
  - |
    VIM_EXE=$HOME/out/8/bin/vim
    echo 'Running Vim 8.1+ tests.' \
      && $VIM_EXE --version \
      && ./run_tests.sh --vim
        \ --vim_exe=$VIM_EXE --international
